version: '3.8'
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
  server:
    container_name: server
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3333:3333'

networks:
  freecodecamp: